import AnimatedDisclosure from "@/components/help/AnimatedDisclosure";
import DocArticle from "@/components/docs/DocArticle";
const questions = [
  ["Is Astral SQL free?", "Yes. The Astral source is MIT-licensed. Dependencies and bundled fonts retain their own licenses. The current release is a beta."],
  ["Which databases can I connect to?", "The desktop app supports SQLite, PostgreSQL, MySQL, and MariaDB. The browser playground runs SQLite locally. Other engines have not been validated."],
  ["Can I connect to my phpMyAdmin database?", "Yes, if the database server permits your desktop connection. phpMyAdmin is a web administration tool, not a database endpoint. Use a database host and port, with a database account. The remote connection guide covers SSH tunnels, direct access, and hosting providers."],
  ["Do my queries pass through Astral’s servers?", "Desktop queries go directly from your computer to your database. Astral has no cloud query relay or app telemetry. Remote database traffic still travels over your network; use TLS or an SSH tunnel to protect it."],
  ["Where are passwords saved?", "When you choose to remember a password in the desktop app, Astral uses the operating system keychain. Connection profiles omit passwords. Otherwise, the password is kept for the active session. Avoid putting passwords in SQL scripts or saved queries."],
  ["Why does Windows show Unknown publisher?", "The beta installer is unsigned and does not yet have a trusted publisher identity. SmartScreen can warn about unfamiliar downloads. This does not prove that a file is safe or that it contains malware. A named antivirus detection needs separate investigation; do not disable protection to install Astral."],
  ["Can I import .sql and .db files?", "Yes. Open a SQLite database file as a database, or open a SQL file in the editor and review it before running the script against the intended connection. SQL imports do not convert one engine’s dialect into another."],
  ["Does it work on Linux, Mac, or iPhone?", "Windows has a downloadable beta. Linux and macOS source-build instructions are available; their install packages have not been released or verified. The site and docs work on phones, but there is no native iOS app."],
  ["Why do I get Connection refused or Connection timed out?", "Those errors usually occur before SQL or password validation. Check the database listener, correct port, server firewall, IP allowlist, and any SSH tunnel. The remote guide explains each error separately."],
  ["Is everything production-ready?", "The core database workflows have automated coverage, but Astral is still beta. Signing, clean-machine installation, cross-platform packaging, and external server/TLS validation remain release gates. Startup and memory targets are not verified benchmarks."],
];
export default function FaqPage() { return <DocArticle title="A few things worth knowing." description="Straight answers about connections, privacy, downloads, and the beta." sections={[{ id: "questions", title: "Common questions" }, { id: "help", title: "Still need help?" }]} previous={{ href: "/docs/connections", title: "Remote connections" }} next={{ href: "/docs/source", title: "Source & contributing" }}>
  <section id="questions" className="docs-faq">{questions.map(([title, body]) => <AnimatedDisclosure key={title} title={title}><p>{body}</p></AnimatedDisclosure>)}</section>
  <section id="help"><h2>Still need help?</h2><p>For server connection failures, follow the <a href="/docs/connections#troubleshooting">connection guide</a>. For a reproducible app problem, <a href="https://github.com/Kraksz/AstralSQL/issues" target="_blank" rel="noreferrer">open a GitHub issue</a> with your app version, operating system, database engine, and the error message. Remove passwords, connection strings, and private data first.</p></section>
  </DocArticle>; }
