import DocArticle from "@/components/docs/DocArticle";
export default function QueryingPage() {
  return <DocArticle title="From a query to an answer." description="A short tour of connections, SQL files, results, and saved work." sections={[{ id: "open", title: "Open your database" }, { id: "run", title: "Run SQL" }, { id: "scripts", title: "Import a SQL script" }, { id: "results", title: "Work with results" }, { id: "manage", title: "Manage tables and databases" }]} previous={{ href: "/docs/install", title: "Installation" }} next={{ href: "/docs/connections", title: "Remote connections" }}>
    <section id="open"><h2>Open your database</h2><p>Use the file action for an existing SQLite <code>.db</code>, <code>.sqlite</code>, or <code>.sqlite3</code> file. For PostgreSQL, MySQL, and MariaDB, add a connection with the database hostname, port, database name, and account credentials.</p><p>A <code>.sql</code> file contains SQL text; it is not a SQLite database file. Opening a script places it in the editor for review.</p></section>
    <section id="run"><h2>Run SQL</h2><pre><code>{"SELECT 1 AS connected;"}</code></pre><p>Choose Run query, or use Ctrl+Enter on Windows/Linux and Cmd+Enter on macOS. Select part of a script to run that selection. Query errors appear in the workspace so you can correct the SQL and retry.</p><p>Use the row limit to keep result sets manageable. Save useful queries in your library and open another tab when you need a separate scratchpad.</p></section>
    <section id="scripts"><h2>Import a SQL script</h2><ol><li>Open the SQL file in the editor.</li><li>Select the intended database connection and review the statements.</li><li>Choose Run SQL script and read the import review before executing.</li><li>Refresh the schema and query the imported table to check the result.</li></ol><div className="docs-note"><p>Use a dump that matches the target engine. A phpMyAdmin MySQL/MariaDB export is not automatically converted to SQLite. Some engine-specific dump commands may need adjustment. Review destructive statements and use a database backup before a large import.</p></div></section>
    <section id="results"><h2>Work with results</h2><p>Filter the returned rows, inspect cells, and export your result set as CSV or JSON. The export contains the returned result set, not every row in the database. Change the row limit and rerun if you need more rows.</p><p>To delete a row, run a <code>SELECT</code> on one table with its primary key in the result, then choose the row&apos;s trash button or right-click the row. The exact <code>DELETE</code> statement is shown before it runs.</p><p>Browser file saving and permissions depend on your browser. If a download is blocked, check its downloads panel. Other in-grid editing and interactive transaction management are not part of this beta; use SQL for other changes.</p></section>
    <section id="manage"><h2>Manage tables and databases</h2><p>Hover a table in the sidebar and choose its trash button to drop it. The trash button beside the table count drops every table and view. Both ask you to type the table or database name first, and neither can be undone.</p><p>For MySQL and MariaDB in the desktop app, the export button writes every table&apos;s structure and rows, plus views, into one <code>.sql</code> file that also imports in phpMyAdmin. The import button runs a <code>.sql</code> dump of up to 1 GiB statement by statement, with progress and a stop button.</p><div className="docs-note"><p>Stored routines, triggers and events are not exported. If an import statement fails, the statements before it stay applied, so export a backup before importing into a database you need.</p></div></section>
  </DocArticle>;
}
