import DocArticle from "@/components/docs/DocArticle";
export default function InstallPage() {
  return <DocArticle title="Make yourself at home." description="Choose the right setup for your computer. Windows has a downloadable beta; Linux and macOS currently use source builds." sections={[{ id: "windows", title: "Windows" }, { id: "linux", title: "Linux" }, { id: "macos", title: "macOS" }, { id: "ios", title: "iPhone & iPad" }]} previous={{ href: "/docs", title: "Welcome to Astral" }} next={{ href: "/docs/querying", title: "Your first query" }}>
    <section id="windows"><h2>Windows <span className="docs-status">BETA DOWNLOAD</span></h2><p>Use Windows 10 or 11 on an x64 PC with Microsoft WebView2 installed.</p><a className="cta-primary" href="/downloads/Astral-SQL-Setup.exe?v=0.1.7" download>Download Windows installer ↓</a><p>The installer is unsigned. A SmartScreen “Unknown publisher” warning concerns publisher identity and reputation; it is not the same as a named malware detection. Do not disable Windows protection. See the <a href="/docs/faq">FAQ</a> and <a href="https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/smartscreen-reputation" target="_blank" rel="noreferrer">Microsoft’s explanation</a>.</p></section>
    <section id="linux"><h2>Linux <span className="docs-status">SOURCE BUILD</span></h2><p>Prebuilt Linux packages have not been released or verified yet. You can build the desktop app on a Linux machine using Node.js 24, Rust, and Tauri’s system dependencies.</p><p>On Debian/Ubuntu, install the required development libraries and a Secret Service provider for keychain support:</p><pre><code>{"sudo apt update\nsudo apt install build-essential curl wget file libwebkit2gtk-4.1-dev libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev libsecret-1-dev libdbus-1-dev pkg-config"}</code></pre><p>Install Rust with its official installer and Node.js 24, then clone the source:</p><pre><code>{"git clone https://github.com/Kraksz/AstralSQL.git\ncd AstralSQL\nnpm ci\nnpm run desktop:build -- --bundles deb,appimage"}</code></pre><p>Generated packages go into <code>target/release/bundle</code>. Build on the oldest distribution you intend to support and test the resulting package there. For other distributions, follow the <a href="https://v2.tauri.app/start/prerequisites/#linux" target="_blank" rel="noreferrer">official Tauri prerequisites</a>.</p></section>
    <section id="macos"><h2>macOS <span className="docs-status">SOURCE BUILD</span></h2><p>There is no signed or notarized Mac download yet. Build on a Mac with Xcode command line tools, Node.js 24, and Rust installed.</p><pre><code>{"xcode-select --install\ngit clone https://github.com/Kraksz/AstralSQL.git\ncd AstralSQL\nnpm ci\nnpm run desktop:build -- --bundles dmg"}</code></pre><p>The DMG is written under <code>target/release/bundle/dmg</code>. A local build is not a verified public release. Distribution needs signing, notarization, and testing on supported Macs. See <a href="https://v2.tauri.app/start/prerequisites/#macos" target="_blank" rel="noreferrer">Tauri’s Mac setup</a>.</p></section>
    <section id="ios"><h2>iPhone & iPad</h2><p>The website and documentation are available on phones. Astral does not currently provide an iOS app, App Store download, or remote database client for iPhone/iPad. macOS is the desktop Mac platform; its build cannot be installed on iOS.</p></section>
  </DocArticle>;
}
